// Generated by demo/export_static_demo.py — real engine output.
window.DEMO_DATA = {
 "generated_at": "2026-07-18T18:09:27.787195+00:00",
 "narration_lang": "es",
 "qwen_live": false,
 "samples": [
  {
   "id": "wolf-1",
   "label": {
    "en": "rapport",
    "es": "rapport",
    "zh": "建立关系"
   },
   "user_id": "wolf",
   "text": "Hi Anna! Great meeting you at the audit-tech conference last week. Your talk on tamper-evident logs was excellent. Would love to stay in touch.",
   "result": {
    "verdict": "SILENT",
    "score": {
     "exact": "0/1",
     "percent": 0
    },
    "active_agents": [
     "L1_GRICE",
     "L6_PEIRCE"
    ],
    "silent_agents": [
     "L2_CARNEGIE",
     "L3_ARISTOTLE",
     "L4_BERNE",
     "L5_LINGUISTIC"
    ],
    "crashed_agents": [],
    "recommendation": "No action required. Baseline updated.",
    "devils_advocate": "Peirce synthesis concluded 'Isolated Gricean violation of maxim RELATION: Topic drift: only 0% vocabulary overlap between halves' based on 1/5 active layers (Grice Cooperative Principle). However, 4 layer(s) found no anomaly: Carnegie/Cialdini Influence Detection and Aristotelian Rhetoric Imbalance and Berne Transactional Analysis and Linguistic Complexity & Register. The strongest counter-hypothesis: the active layers may have fired on surface-level lexical features (urgency markers, authority claims, emotional language) that are also present in legitimate high-stakes communication — legal notices, medical advisories, crisis management. The silent dimensions suggest the underlying transaction structure and linguistic register do not deviate from baseline, which is inconsistent with systematic manipulation. This finding should be treated as WATCH rather than ALERT without additional behavioral context.",
    "audit": {
     "signal_hash": "d6c39ef1323a399bfa89b656dda120f699fd1baabd4c1125d9b29d13363fd0a5",
     "verdict_hash": "c2b3c1a7b8e053977968d0c34851861587f5f3f71fc86c6d58cda3bd0f9e1d22",
     "trace_ids": {
      "L1_GRICE": "7893e613-71dd-41f8-beb9-e659ac434692",
      "L2_CARNEGIE": "ed59cb0e-e33d-43a3-9112-fd9391ae2de8",
      "L3_ARISTOTLE": "d39aee22-87ac-40b4-bca0-96391b68e198",
      "L4_BERNE": "22ac1347-f7a4-4e7e-b5b5-787310348f27",
      "L5_LINGUISTIC": "ab18b108-9e2b-4831-a62c-974a030b24cf",
      "L6_PEIRCE": "9b2a4f79-1852-4e02-914a-0bc38b27d7bf",
      "GATE": "3d4fb681-f86f-43c8-aa56-4de86c14b39c"
     },
     "chain_valid": true,
     "warnings": []
    },
    "narration": {
     "requested": true,
     "lang": "es",
     "text": null,
     "note": "Narration offline — DASHSCOPE_API_KEY not configured. The sealed verdict below is complete without it."
    }
   },
   "chain": {
    "verify": {
     "chain_ok": true,
     "errors": []
    },
    "traces": [
     {
      "trace_id": "3d4fb681-f86f-43c8-aa56-4de86c14b39c",
      "agent_id": "GATE",
      "objective": "Corroboration gate: require >= 2 active agents for any verdict above SILENT",
      "decision": "SILENT",
      "confidence": "3/5",
      "closed_at": "2026-07-18T18:09:27.646030+00:00",
      "entry_hash": "69890355babb3cee729ac73ec142e7a53d156f9249976854a5a1891d76b1aa9e",
      "chain_ok": 1
     },
     {
      "trace_id": "9b2a4f79-1852-4e02-914a-0bc38b27d7bf",
      "agent_id": "L6_PEIRCE",
      "objective": "[Peirce Abductive Synthesis] Synthesize: api",
      "decision": "SIGNAL_DETECTED",
      "confidence": "17/20",
      "closed_at": "2026-07-18T18:09:27.644572+00:00",
      "entry_hash": "4653565efc93f93c2e88f45e1c9a76f3a3366df182071af3c62edc47493fb4eb",
      "chain_ok": 1
     },
     {
      "trace_id": "ab18b108-9e2b-4831-a62c-974a030b24cf",
      "agent_id": "L5_LINGUISTIC",
      "objective": "[Linguistic Complexity & Register] Analyze: api",
      "decision": "SILENT",
      "confidence": "17/20",
      "closed_at": "2026-07-18T18:09:27.642779+00:00",
      "entry_hash": "b562e5a58ee34d90bf5feb967eaa610313d3d7e7cdd78c5dfcb2f57857f05154",
      "chain_ok": 1
     },
     {
      "trace_id": "22ac1347-f7a4-4e7e-b5b5-787310348f27",
      "agent_id": "L4_BERNE",
      "objective": "[Berne Transactional Analysis] Analyze: api",
      "decision": "SILENT",
      "confidence": "17/20",
      "closed_at": "2026-07-18T18:09:27.641348+00:00",
      "entry_hash": "bf1094de8da3f6e232212c7ffc3c452677f34efd78445e765ad2046b151d5034",
      "chain_ok": 1
     },
     {
      "trace_id": "d39aee22-87ac-40b4-bca0-96391b68e198",
      "agent_id": "L3_ARISTOTLE",
      "objective": "[Aristotelian Rhetoric Imbalance] Analyze: api",
      "decision": "SILENT",
      "confidence": "17/20",
      "closed_at": "2026-07-18T18:09:27.639879+00:00",
      "entry_hash": "69b9e65b505ae25b414b6a99ac47680c6cd0cf0b9730d9b5e1abab97620b5c00",
      "chain_ok": 1
     },
     {
      "trace_id": "ed59cb0e-e33d-43a3-9112-fd9391ae2de8",
      "agent_id": "L2_CARNEGIE",
      "objective": "[Carnegie/Cialdini Influence Detection] Analyze: api",
      "decision": "SILENT",
      "confidence": "17/20",
      "closed_at": "2026-07-18T18:09:27.638420+00:00",
      "entry_hash": "e08fe4b4f92494bbc75cd39addf1a0dc7a7dba9912642da052899a59f310b87c",
      "chain_ok": 1
     },
     {
      "trace_id": "7893e613-71dd-41f8-beb9-e659ac434692",
      "agent_id": "L1_GRICE",
      "objective": "[Grice Cooperative Principle] Analyze: api",
      "decision": "SIGNAL_DETECTED",
      "confidence": "1/5",
      "closed_at": "2026-07-18T18:09:27.637008+00:00",
      "entry_hash": "8010f87224d5a821c654142fb1a59fd774900a551ad0c310c172b37affd3262e",
      "chain_ok": 1
     }
    ]
   }
  },
  {
   "id": "wolf-2",
   "label": {
    "en": "flattery",
    "es": "halago",
    "zh": "奉承"
   },
   "user_id": "wolf",
   "text": "You're honestly one of the very few people who truly understands this space. That's exactly why I thought of you first for something special.",
   "result": {
    "verdict": "SILENT",
    "score": {
     "exact": "0/1",
     "percent": 0
    },
    "active_agents": [
     "L1_GRICE",
     "L6_PEIRCE"
    ],
    "silent_agents": [
     "L2_CARNEGIE",
     "L3_ARISTOTLE",
     "L4_BERNE",
     "L5_LINGUISTIC"
    ],
    "crashed_agents": [],
    "recommendation": "No action required. Baseline updated.",
    "devils_advocate": "Peirce synthesis concluded 'Isolated Gricean violation of maxim RELATION: Topic drift: only 0% vocabulary overlap between halves' based on 1/5 active layers (Grice Cooperative Principle). However, 4 layer(s) found no anomaly: Carnegie/Cialdini Influence Detection and Aristotelian Rhetoric Imbalance and Berne Transactional Analysis and Linguistic Complexity & Register. The strongest counter-hypothesis: the active layers may have fired on surface-level lexical features (urgency markers, authority claims, emotional language) that are also present in legitimate high-stakes communication — legal notices, medical advisories, crisis management. The silent dimensions suggest the underlying transaction structure and linguistic register do not deviate from baseline, which is inconsistent with systematic manipulation. This finding should be treated as WATCH rather than ALERT without additional behavioral context.",
    "audit": {
     "signal_hash": "ccfb9cd0684441c3402b60c0079b9c6089f96b74fcf15138b98c8a432f16ecfe",
     "verdict_hash": "1b9d42091582520e57991b4146443c3f7662acd425ff7fd5b6a284b911e1476b",
     "trace_ids": {
      "L1_GRICE": "8f9d36ac-1d08-45d8-a62b-8b6b3f369a74",
      "L2_CARNEGIE": "5b685e7f-0fa3-4b31-87e2-a77ae6ca4706",
      "L3_ARISTOTLE": "fbf64452-ea36-47a3-9814-6bbb17e60e88",
      "L4_BERNE": "7d470a4c-1e22-4e0d-b719-be90855467aa",
      "L5_LINGUISTIC": "4f87b012-426d-4bd4-a606-bea1b13de3cc",
      "L6_PEIRCE": "06eff122-ccab-4d83-8fd1-ab38ecd07dc9",
      "GATE": "d3016319-e9da-4c0f-9567-f84b4d58b6a2"
     },
     "chain_valid": true,
     "warnings": []
    },
    "narration": {
     "requested": true,
     "lang": "es",
     "text": null,
     "note": "Narration offline — DASHSCOPE_API_KEY not configured. The sealed verdict below is complete without it."
    }
   },
   "chain": {
    "verify": {
     "chain_ok": true,
     "errors": []
    },
    "traces": [
     {
      "trace_id": "d3016319-e9da-4c0f-9567-f84b4d58b6a2",
      "agent_id": "GATE",
      "objective": "Corroboration gate: require >= 2 active agents for any verdict above SILENT",
      "decision": "SILENT",
      "confidence": "3/5",
      "closed_at": "2026-07-18T18:09:27.664003+00:00",
      "entry_hash": "6cd55635c011cdb26f59868f28eb7b2a8a8051949c68d0490bddeeab5fd4d683",
      "chain_ok": 1
     },
     {
      "trace_id": "06eff122-ccab-4d83-8fd1-ab38ecd07dc9",
      "agent_id": "L6_PEIRCE",
      "objective": "[Peirce Abductive Synthesis] Synthesize: api",
      "decision": "SIGNAL_DETECTED",
      "confidence": "1/5",
      "closed_at": "2026-07-18T18:09:27.662524+00:00",
      "entry_hash": "a8ac97eddfba319655516d17bfb382e5da68ad3926e98f90a3dcbfdf91a5c69e",
      "chain_ok": 1
     },
     {
      "trace_id": "4f87b012-426d-4bd4-a606-bea1b13de3cc",
      "agent_id": "L5_LINGUISTIC",
      "objective": "[Linguistic Complexity & Register] Analyze: api",
      "decision": "SILENT",
      "confidence": "17/20",
      "closed_at": "2026-07-18T18:09:27.661025+00:00",
      "entry_hash": "86cc3f573c325ce2acf23a86f2f2875b4e98c2d8c68fd8f85f14461c47996597",
      "chain_ok": 1
     },
     {
      "trace_id": "7d470a4c-1e22-4e0d-b719-be90855467aa",
      "agent_id": "L4_BERNE",
      "objective": "[Berne Transactional Analysis] Analyze: api",
      "decision": "SILENT",
      "confidence": "17/20",
      "closed_at": "2026-07-18T18:09:27.659589+00:00",
      "entry_hash": "9e11d22e0d17b96ca356266cd34b40a39231d03026f68f282cc9bb78b82c641e",
      "chain_ok": 1
     },
     {
      "trace_id": "fbf64452-ea36-47a3-9814-6bbb17e60e88",
      "agent_id": "L3_ARISTOTLE",
      "objective": "[Aristotelian Rhetoric Imbalance] Analyze: api",
      "decision": "SILENT",
      "confidence": "17/20",
      "closed_at": "2026-07-18T18:09:27.658166+00:00",
      "entry_hash": "a3e9431baae240cddb22608c9ea1218078790fc1e816db3f005ebe3443548679",
      "chain_ok": 1
     },
     {
      "trace_id": "5b685e7f-0fa3-4b31-87e2-a77ae6ca4706",
      "agent_id": "L2_CARNEGIE",
      "objective": "[Carnegie/Cialdini Influence Detection] Analyze: api",
      "decision": "SILENT",
      "confidence": "17/20",
      "closed_at": "2026-07-18T18:09:27.656679+00:00",
      "entry_hash": "f938293bf7549676d548a57046ad7449990b7973a337bb68de920be6af74c0b6",
      "chain_ok": 1
     },
     {
      "trace_id": "8f9d36ac-1d08-45d8-a62b-8b6b3f369a74",
      "agent_id": "L1_GRICE",
      "objective": "[Grice Cooperative Principle] Analyze: api",
      "decision": "SIGNAL_DETECTED",
      "confidence": "1/5",
      "closed_at": "2026-07-18T18:09:27.655228+00:00",
      "entry_hash": "f6d04dda2df2acb6a331b8e23680eeb2df386e7ac1f9b653560d92f64ed9f45b",
      "chain_ok": 1
     },
     {
      "trace_id": "3d4fb681-f86f-43c8-aa56-4de86c14b39c",
      "agent_id": "GATE",
      "objective": "Corroboration gate: require >= 2 active agents for any verdict above SILENT",
      "decision": "SILENT",
      "confidence": "3/5",
      "closed_at": "2026-07-18T18:09:27.646030+00:00",
      "entry_hash": "69890355babb3cee729ac73ec142e7a53d156f9249976854a5a1891d76b1aa9e",
      "chain_ok": 1
     }
    ]
   }
  },
  {
   "id": "wolf-3",
   "label": {
    "en": "scarcity + secrecy",
    "es": "escasez + secreto",
    "zh": "稀缺 + 保密"
   },
   "user_id": "wolf",
   "text": "Between us — there's a private allocation round closing soon. Only insiders know about it. I can get you in, but you'd have to move quickly before it's shut down.",
   "result": {
    "verdict": "SILENT",
    "score": {
     "exact": "0/1",
     "percent": 0
    },
    "active_agents": [
     "L1_GRICE",
     "L6_PEIRCE"
    ],
    "silent_agents": [
     "L2_CARNEGIE",
     "L3_ARISTOTLE",
     "L4_BERNE",
     "L5_LINGUISTIC"
    ],
    "crashed_agents": [],
    "recommendation": "No action required. Baseline updated.",
    "devils_advocate": "Peirce synthesis concluded 'Isolated Gricean violation of maxim RELATION: Topic drift: only 0% vocabulary overlap between halves' based on 1/5 active layers (Grice Cooperative Principle). However, 4 layer(s) found no anomaly: Carnegie/Cialdini Influence Detection and Aristotelian Rhetoric Imbalance and Berne Transactional Analysis and Linguistic Complexity & Register. The strongest counter-hypothesis: the active layers may have fired on surface-level lexical features (urgency markers, authority claims, emotional language) that are also present in legitimate high-stakes communication — legal notices, medical advisories, crisis management. The silent dimensions suggest the underlying transaction structure and linguistic register do not deviate from baseline, which is inconsistent with systematic manipulation. This finding should be treated as WATCH rather than ALERT without additional behavioral context.",
    "audit": {
     "signal_hash": "ccfb9cd0684441c3402b60c0079b9c6089f96b74fcf15138b98c8a432f16ecfe",
     "verdict_hash": "1b9d42091582520e57991b4146443c3f7662acd425ff7fd5b6a284b911e1476b",
     "trace_ids": {
      "L1_GRICE": "1004765a-0a8a-4bae-88f6-fd9d5fb91aa5",
      "L2_CARNEGIE": "3b6c7794-ee4f-4986-bbe0-c313ea9616d1",
      "L3_ARISTOTLE": "cc99ed0f-6eb3-49e9-add2-1fe4541be4fa",
      "L4_BERNE": "163901e4-f211-4e82-908a-67e29249597d",
      "L5_LINGUISTIC": "d8d91221-5a72-4bc8-96db-7d2cd4b9dd54",
      "L6_PEIRCE": "2e9d7dc7-470a-44ac-b106-7b5e5d9e518d",
      "GATE": "84df538f-d917-4859-9a76-9907a4ec7993"
     },
     "chain_valid": true,
     "warnings": []
    },
    "narration": {
     "requested": true,
     "lang": "es",
     "text": null,
     "note": "Narration offline — DASHSCOPE_API_KEY not configured. The sealed verdict below is complete without it."
    }
   },
   "chain": {
    "verify": {
     "chain_ok": true,
     "errors": []
    },
    "traces": [
     {
      "trace_id": "84df538f-d917-4859-9a76-9907a4ec7993",
      "agent_id": "GATE",
      "objective": "Corroboration gate: require >= 2 active agents for any verdict above SILENT",
      "decision": "SILENT",
      "confidence": "3/5",
      "closed_at": "2026-07-18T18:09:27.682562+00:00",
      "entry_hash": "72f3512e24ceb17e6ad7751696075bf420480a19aedb664dde4431a9113e6244",
      "chain_ok": 1
     },
     {
      "trace_id": "2e9d7dc7-470a-44ac-b106-7b5e5d9e518d",
      "agent_id": "L6_PEIRCE",
      "objective": "[Peirce Abductive Synthesis] Synthesize: api",
      "decision": "SIGNAL_DETECTED",
      "confidence": "1/5",
      "closed_at": "2026-07-18T18:09:27.680737+00:00",
      "entry_hash": "590643690a435781c3160ef0964692fc11c346f2c79ffc5321e0711321649558",
      "chain_ok": 1
     },
     {
      "trace_id": "d8d91221-5a72-4bc8-96db-7d2cd4b9dd54",
      "agent_id": "L5_LINGUISTIC",
      "objective": "[Linguistic Complexity & Register] Analyze: api",
      "decision": "SILENT",
      "confidence": "17/20",
      "closed_at": "2026-07-18T18:09:27.679060+00:00",
      "entry_hash": "72d37ed2f77a2aac4926af708ea1cf426727f1a32a3d59ff098da72bc6a03aa7",
      "chain_ok": 1
     },
     {
      "trace_id": "163901e4-f211-4e82-908a-67e29249597d",
      "agent_id": "L4_BERNE",
      "objective": "[Berne Transactional Analysis] Analyze: api",
      "decision": "SILENT",
      "confidence": "17/20",
      "closed_at": "2026-07-18T18:09:27.677591+00:00",
      "entry_hash": "6d7444bfafad4ca8247d940de489dcd75d03ccc098f23eaf006c50093403a359",
      "chain_ok": 1
     },
     {
      "trace_id": "cc99ed0f-6eb3-49e9-add2-1fe4541be4fa",
      "agent_id": "L3_ARISTOTLE",
      "objective": "[Aristotelian Rhetoric Imbalance] Analyze: api",
      "decision": "SILENT",
      "confidence": "17/20",
      "closed_at": "2026-07-18T18:09:27.675609+00:00",
      "entry_hash": "53ecdf70734deea9b23b6fdb4225f534c9a6414414db44ff6e34818320bd4256",
      "chain_ok": 1
     },
     {
      "trace_id": "3b6c7794-ee4f-4986-bbe0-c313ea9616d1",
      "agent_id": "L2_CARNEGIE",
      "objective": "[Carnegie/Cialdini Influence Detection] Analyze: api",
      "decision": "SILENT",
      "confidence": "17/20",
      "closed_at": "2026-07-18T18:09:27.674174+00:00",
      "entry_hash": "ac004b0bbe543e48e7bffb6b21f711bbb2b206c45589ceef76e06dcddf18b11f",
      "chain_ok": 1
     },
     {
      "trace_id": "1004765a-0a8a-4bae-88f6-fd9d5fb91aa5",
      "agent_id": "L1_GRICE",
      "objective": "[Grice Cooperative Principle] Analyze: api",
      "decision": "SIGNAL_DETECTED",
      "confidence": "1/5",
      "closed_at": "2026-07-18T18:09:27.672721+00:00",
      "entry_hash": "e603e44643067b88e1a65b32da934455da5f7885bbfca8b631fe13b866812d59",
      "chain_ok": 1
     },
     {
      "trace_id": "d3016319-e9da-4c0f-9567-f84b4d58b6a2",
      "agent_id": "GATE",
      "objective": "Corroboration gate: require >= 2 active agents for any verdict above SILENT",
      "decision": "SILENT",
      "confidence": "3/5",
      "closed_at": "2026-07-18T18:09:27.664003+00:00",
      "entry_hash": "6cd55635c011cdb26f59868f28eb7b2a8a8051949c68d0490bddeeab5fd4d683",
      "chain_ok": 1
     }
    ]
   }
  },
  {
   "id": "wolf-4",
   "label": {
    "en": "authority + proof",
    "es": "autoridad + prueba social",
    "zh": "权威 + 社会认同"
   },
   "user_id": "wolf",
   "text": "I've been advising funds for 15 years, so trust me on this. Everyone in your network has already committed. You don't want to be the only one left out when this becomes public.",
   "result": {
    "verdict": "SILENT",
    "score": {
     "exact": "0/1",
     "percent": 0
    },
    "active_agents": [
     "L1_GRICE",
     "L6_PEIRCE"
    ],
    "silent_agents": [
     "L2_CARNEGIE",
     "L3_ARISTOTLE",
     "L4_BERNE",
     "L5_LINGUISTIC"
    ],
    "crashed_agents": [],
    "recommendation": "No action required. Baseline updated.",
    "devils_advocate": "Peirce synthesis concluded 'Isolated Gricean violation of maxim RELATION: Topic drift: only 0% vocabulary overlap between halves' based on 1/5 active layers (Grice Cooperative Principle). However, 4 layer(s) found no anomaly: Carnegie/Cialdini Influence Detection and Aristotelian Rhetoric Imbalance and Berne Transactional Analysis and Linguistic Complexity & Register. The strongest counter-hypothesis: the active layers may have fired on surface-level lexical features (urgency markers, authority claims, emotional language) that are also present in legitimate high-stakes communication — legal notices, medical advisories, crisis management. The silent dimensions suggest the underlying transaction structure and linguistic register do not deviate from baseline, which is inconsistent with systematic manipulation. This finding should be treated as WATCH rather than ALERT without additional behavioral context.",
    "audit": {
     "signal_hash": "ccfb9cd0684441c3402b60c0079b9c6089f96b74fcf15138b98c8a432f16ecfe",
     "verdict_hash": "1b9d42091582520e57991b4146443c3f7662acd425ff7fd5b6a284b911e1476b",
     "trace_ids": {
      "L1_GRICE": "c30c5aad-aa89-4cd3-847b-31bcc3cf1cb3",
      "L2_CARNEGIE": "be156b39-0e29-4031-9db7-981b36d5c8d4",
      "L3_ARISTOTLE": "d621e6b1-8683-4202-8e94-65a22ee4a3ad",
      "L4_BERNE": "ee840775-294d-4c38-a5cb-e07b9378fe67",
      "L5_LINGUISTIC": "7611e0d5-c0b1-4471-82e0-e5506e44e07f",
      "L6_PEIRCE": "c2a098cd-1a64-42dc-98a5-afd8a409b58a",
      "GATE": "4dfb1c22-7a11-4be6-8fa8-09ce328491b0"
     },
     "chain_valid": true,
     "warnings": []
    },
    "narration": {
     "requested": true,
     "lang": "es",
     "text": null,
     "note": "Narration offline — DASHSCOPE_API_KEY not configured. The sealed verdict below is complete without it."
    }
   },
   "chain": {
    "verify": {
     "chain_ok": true,
     "errors": []
    },
    "traces": [
     {
      "trace_id": "4dfb1c22-7a11-4be6-8fa8-09ce328491b0",
      "agent_id": "GATE",
      "objective": "Corroboration gate: require >= 2 active agents for any verdict above SILENT",
      "decision": "SILENT",
      "confidence": "3/5",
      "closed_at": "2026-07-18T18:09:27.700338+00:00",
      "entry_hash": "80794ed7bc462f76be21a2ae3631b76c40e122647a35a6b2fc188b1bdb59b983",
      "chain_ok": 1
     },
     {
      "trace_id": "c2a098cd-1a64-42dc-98a5-afd8a409b58a",
      "agent_id": "L6_PEIRCE",
      "objective": "[Peirce Abductive Synthesis] Synthesize: api",
      "decision": "SIGNAL_DETECTED",
      "confidence": "1/5",
      "closed_at": "2026-07-18T18:09:27.698912+00:00",
      "entry_hash": "ba061703c6c182b5b3243b9e2c1e9b8adbaea2968b3f0c3703e4686b6925423a",
      "chain_ok": 1
     },
     {
      "trace_id": "7611e0d5-c0b1-4471-82e0-e5506e44e07f",
      "agent_id": "L5_LINGUISTIC",
      "objective": "[Linguistic Complexity & Register] Analyze: api",
      "decision": "SILENT",
      "confidence": "17/20",
      "closed_at": "2026-07-18T18:09:27.697427+00:00",
      "entry_hash": "0e91df707702206111475cbde9a4dd6432d6388effad47834edf7fb7ab9ea1dc",
      "chain_ok": 1
     },
     {
      "trace_id": "ee840775-294d-4c38-a5cb-e07b9378fe67",
      "agent_id": "L4_BERNE",
      "objective": "[Berne Transactional Analysis] Analyze: api",
      "decision": "SILENT",
      "confidence": "17/20",
      "closed_at": "2026-07-18T18:09:27.695965+00:00",
      "entry_hash": "96583316400686dd0365ee673945838d8690a01afbc03061a1ad1a5e849a2daa",
      "chain_ok": 1
     },
     {
      "trace_id": "d621e6b1-8683-4202-8e94-65a22ee4a3ad",
      "agent_id": "L3_ARISTOTLE",
      "objective": "[Aristotelian Rhetoric Imbalance] Analyze: api",
      "decision": "SILENT",
      "confidence": "17/20",
      "closed_at": "2026-07-18T18:09:27.694510+00:00",
      "entry_hash": "b30fc0db60371ed5e468afad4f5173eca160b714edf419998864a737e5ed3d06",
      "chain_ok": 1
     },
     {
      "trace_id": "be156b39-0e29-4031-9db7-981b36d5c8d4",
      "agent_id": "L2_CARNEGIE",
      "objective": "[Carnegie/Cialdini Influence Detection] Analyze: api",
      "decision": "SILENT",
      "confidence": "17/20",
      "closed_at": "2026-07-18T18:09:27.693073+00:00",
      "entry_hash": "4a99859f927927ac0a5a585be3483590185215f81524da9d9daef1190c22b3a6",
      "chain_ok": 1
     },
     {
      "trace_id": "c30c5aad-aa89-4cd3-847b-31bcc3cf1cb3",
      "agent_id": "L1_GRICE",
      "objective": "[Grice Cooperative Principle] Analyze: api",
      "decision": "SIGNAL_DETECTED",
      "confidence": "1/5",
      "closed_at": "2026-07-18T18:09:27.691615+00:00",
      "entry_hash": "bda67dd83c2e02a3416ce49e16b089d74c6b2ef338f29d91371b8e16c88edc74",
      "chain_ok": 1
     },
     {
      "trace_id": "84df538f-d917-4859-9a76-9907a4ec7993",
      "agent_id": "GATE",
      "objective": "Corroboration gate: require >= 2 active agents for any verdict above SILENT",
      "decision": "SILENT",
      "confidence": "3/5",
      "closed_at": "2026-07-18T18:09:27.682562+00:00",
      "entry_hash": "72f3512e24ceb17e6ad7751696075bf420480a19aedb664dde4431a9113e6244",
      "chain_ok": 1
     }
    ]
   }
  },
  {
   "id": "wolf-5",
   "label": {
    "en": "urgency + guilt",
    "es": "urgencia + culpa",
    "zh": "紧迫 + 内疚"
   },
   "user_id": "wolf",
   "text": "After everything I've shared with you, the least you can do is act now. Wire the deposit in the next 2 hours or you lose the slot forever. Think about your future — are you really willing to gamble everything away?",
   "result": {
    "verdict": "WATCH",
    "score": {
     "exact": "279/1000",
     "percent": 28
    },
    "active_agents": [
     "L1_GRICE",
     "L2_CARNEGIE",
     "L6_PEIRCE"
    ],
    "silent_agents": [
     "L3_ARISTOTLE",
     "L4_BERNE",
     "L5_LINGUISTIC"
    ],
    "crashed_agents": [],
    "recommendation": "Monitor this user's subsequent messages. Flagged for security-team review.",
    "devils_advocate": "Peirce synthesis concluded 'Deliberate obfuscation to embed influence: the message uses complex language to hide manipulation tactics, making the attempt harder to consciously identify.' based on 2/5 active layers (Grice Cooperative Principle, Carnegie/Cialdini Influence Detection). However, 3 layer(s) found no anomaly: Aristotelian Rhetoric Imbalance and Berne Transactional Analysis and Linguistic Complexity & Register. The strongest counter-hypothesis: the active layers may have fired on surface-level lexical features (urgency markers, authority claims, emotional language) that are also present in legitimate high-stakes communication — legal notices, medical advisories, crisis management. The silent dimensions suggest the underlying transaction structure and linguistic register do not deviate from baseline, which is inconsistent with systematic manipulation. This finding should be treated as WATCH rather than ALERT without additional behavioral context.",
    "audit": {
     "signal_hash": "d5c77f07800f9868f0d91b4c408eba5c9619e8a0afe6db23b25baa7cfa506116",
     "verdict_hash": "33941464cfdf84743d3492daae1c45d6d4f8d295aa29ea2506bb7343e5ce89ac",
     "trace_ids": {
      "L1_GRICE": "2235229d-3e80-4961-b3af-9fff073a4297",
      "L2_CARNEGIE": "d54ef526-7172-490d-9aa2-9afb84a79174",
      "L3_ARISTOTLE": "78fc1c42-5f5e-4e17-b1f8-4fa3fb257fa5",
      "L4_BERNE": "40dbfd89-a093-4c63-ada6-2d131234bcbf",
      "L5_LINGUISTIC": "97352a71-c924-4d10-9bfc-2a29c6bde51b",
      "L6_PEIRCE": "6e68336a-e388-4885-ae14-617bee6440d4",
      "GATE": "47793356-3838-409e-8169-033e5ef986ec"
     },
     "chain_valid": true,
     "warnings": []
    },
    "narration": {
     "requested": true,
     "lang": "es",
     "text": null,
     "note": "Narration offline — DASHSCOPE_API_KEY not configured. The sealed verdict below is complete without it."
    }
   },
   "chain": {
    "verify": {
     "chain_ok": true,
     "errors": []
    },
    "traces": [
     {
      "trace_id": "47793356-3838-409e-8169-033e5ef986ec",
      "agent_id": "GATE",
      "objective": "Corroboration gate: require >= 2 active agents for any verdict above SILENT",
      "decision": "WATCH",
      "confidence": "279/1000",
      "closed_at": "2026-07-18T18:09:27.718014+00:00",
      "entry_hash": "9ce085979e2f1ac338b0a07e4a4ce42fea82f0e3a12b143a990698bf9bbaba28",
      "chain_ok": 1
     },
     {
      "trace_id": "6e68336a-e388-4885-ae14-617bee6440d4",
      "agent_id": "L6_PEIRCE",
      "objective": "[Peirce Abductive Synthesis] Synthesize: api",
      "decision": "SIGNAL_DETECTED",
      "confidence": "73/100",
      "closed_at": "2026-07-18T18:09:27.716548+00:00",
      "entry_hash": "ea13e27c006feb3c65c7caefab6c1bfdef4741e54a43e918a0ff9baa0e79eae6",
      "chain_ok": 1
     },
     {
      "trace_id": "97352a71-c924-4d10-9bfc-2a29c6bde51b",
      "agent_id": "L5_LINGUISTIC",
      "objective": "[Linguistic Complexity & Register] Analyze: api",
      "decision": "SILENT",
      "confidence": "17/20",
      "closed_at": "2026-07-18T18:09:27.715061+00:00",
      "entry_hash": "3e848e42a450da2a26b09b9abb257c5f2c8658ad3e42d65680c11bb90c2af54f",
      "chain_ok": 1
     },
     {
      "trace_id": "40dbfd89-a093-4c63-ada6-2d131234bcbf",
      "agent_id": "L4_BERNE",
      "objective": "[Berne Transactional Analysis] Analyze: api",
      "decision": "SILENT",
      "confidence": "17/20",
      "closed_at": "2026-07-18T18:09:27.713590+00:00",
      "entry_hash": "a80f8759bd590f7c2acc36cd60ecc155806aae38c029c7b1900d60a1da289e38",
      "chain_ok": 1
     },
     {
      "trace_id": "78fc1c42-5f5e-4e17-b1f8-4fa3fb257fa5",
      "agent_id": "L3_ARISTOTLE",
      "objective": "[Aristotelian Rhetoric Imbalance] Analyze: api",
      "decision": "SILENT",
      "confidence": "17/20",
      "closed_at": "2026-07-18T18:09:27.712131+00:00",
      "entry_hash": "7404771b0fcef6a2f5db457cecbfa8045d5482c7f13e286feab87adf9b101f33",
      "chain_ok": 1
     },
     {
      "trace_id": "d54ef526-7172-490d-9aa2-9afb84a79174",
      "agent_id": "L2_CARNEGIE",
      "objective": "[Carnegie/Cialdini Influence Detection] Analyze: api",
      "decision": "SIGNAL_DETECTED",
      "confidence": "3/25",
      "closed_at": "2026-07-18T18:09:27.710691+00:00",
      "entry_hash": "46141ce89f6b7bd0a5f083a62ac4293a4c4e399347e5f5be1f9d78eb5ed812ac",
      "chain_ok": 1
     },
     {
      "trace_id": "2235229d-3e80-4961-b3af-9fff073a4297",
      "agent_id": "L1_GRICE",
      "objective": "[Grice Cooperative Principle] Analyze: api",
      "decision": "SIGNAL_DETECTED",
      "confidence": "1/5",
      "closed_at": "2026-07-18T18:09:27.709241+00:00",
      "entry_hash": "e7d6cdccb5a9c7e68b275ef4b9f0f290750342fcc591c46a6a1daf28fc71a8a1",
      "chain_ok": 1
     },
     {
      "trace_id": "4dfb1c22-7a11-4be6-8fa8-09ce328491b0",
      "agent_id": "GATE",
      "objective": "Corroboration gate: require >= 2 active agents for any verdict above SILENT",
      "decision": "SILENT",
      "confidence": "3/5",
      "closed_at": "2026-07-18T18:09:27.700338+00:00",
      "entry_hash": "80794ed7bc462f76be21a2ae3631b76c40e122647a35a6b2fc188b1bdb59b983",
      "chain_ok": 1
     }
    ]
   }
  },
  {
   "id": "benign",
   "label": {
    "en": "benign note",
    "es": "mensaje benigno",
    "zh": "无害消息"
   },
   "user_id": "friend",
   "text": "Hi! Attaching the meeting notes from Tuesday. No rush at all — whenever you get a chance is fine.",
   "result": {
    "verdict": "SILENT",
    "score": {
     "exact": "0/1",
     "percent": 0
    },
    "active_agents": [],
    "silent_agents": [
     "L1_GRICE",
     "L2_CARNEGIE",
     "L3_ARISTOTLE",
     "L4_BERNE",
     "L5_LINGUISTIC",
     "L6_PEIRCE"
    ],
    "crashed_agents": [],
    "recommendation": "No action required. Baseline updated.",
    "devils_advocate": "No layer detected any signal. The strongest benign explanation: text is fully cooperative, expressive, and contextually normal across all five rhetorical dimensions examined.",
    "audit": {
     "signal_hash": "e309babfdb34b542d819b2ebbf60459e70be82c6d3f43198ed10622621ba31cc",
     "verdict_hash": "129285e4e94a34a9de784e13e45e81aa21c11403913c81a2a11991735e5f2d1c",
     "trace_ids": {
      "L1_GRICE": "62baa75b-01a5-4c23-be65-077ac75a1a78",
      "L2_CARNEGIE": "90122e28-c722-4d2e-99ad-44430ad6a87d",
      "L3_ARISTOTLE": "3cdd8ca7-a574-4ebf-9e61-f63608e1dba0",
      "L4_BERNE": "728011ab-c61b-4c0a-bd06-5d4693f5a809",
      "L5_LINGUISTIC": "ec40fe7c-5c26-4c4c-8e92-da65dfd2e3d9",
      "L6_PEIRCE": "9ec81af8-3ee3-4301-9446-5c959d777642",
      "GATE": "fb024946-212b-45a0-9d5c-47b76babe480"
     },
     "chain_valid": true,
     "warnings": []
    },
    "narration": {
     "requested": true,
     "lang": "es",
     "text": null,
     "note": "Narration offline — DASHSCOPE_API_KEY not configured. The sealed verdict below is complete without it."
    }
   },
   "chain": {
    "verify": {
     "chain_ok": true,
     "errors": []
    },
    "traces": [
     {
      "trace_id": "fb024946-212b-45a0-9d5c-47b76babe480",
      "agent_id": "GATE",
      "objective": "Corroboration gate: require >= 2 active agents for any verdict above SILENT",
      "decision": "SILENT",
      "confidence": "3/5",
      "closed_at": "2026-07-18T18:09:27.735195+00:00",
      "entry_hash": "8d22f94885e22eb2c09fbd9d868b7c4cd124fddd67532123303788e00f366617",
      "chain_ok": 1
     },
     {
      "trace_id": "9ec81af8-3ee3-4301-9446-5c959d777642",
      "agent_id": "L6_PEIRCE",
      "objective": "[Peirce Abductive Synthesis] Synthesize: api",
      "decision": "SILENT",
      "confidence": "17/20",
      "closed_at": "2026-07-18T18:09:27.733744+00:00",
      "entry_hash": "40623d6ac84486b7a07decfd7dc907f2c428302ec5689727b8a961d12a6a235b",
      "chain_ok": 1
     },
     {
      "trace_id": "ec40fe7c-5c26-4c4c-8e92-da65dfd2e3d9",
      "agent_id": "L5_LINGUISTIC",
      "objective": "[Linguistic Complexity & Register] Analyze: api",
      "decision": "SILENT",
      "confidence": "17/20",
      "closed_at": "2026-07-18T18:09:27.732276+00:00",
      "entry_hash": "942550ff9b5fa84b498b79e46b87846fb0b33d46dd94e4ccd1acdefb35ec70ab",
      "chain_ok": 1
     },
     {
      "trace_id": "728011ab-c61b-4c0a-bd06-5d4693f5a809",
      "agent_id": "L4_BERNE",
      "objective": "[Berne Transactional Analysis] Analyze: api",
      "decision": "SILENT",
      "confidence": "17/20",
      "closed_at": "2026-07-18T18:09:27.730814+00:00",
      "entry_hash": "e6157eb6efe540eab9c5d731f41dc479631d328d1cc4c98e8ae90364acd16d87",
      "chain_ok": 1
     },
     {
      "trace_id": "3cdd8ca7-a574-4ebf-9e61-f63608e1dba0",
      "agent_id": "L3_ARISTOTLE",
      "objective": "[Aristotelian Rhetoric Imbalance] Analyze: api",
      "decision": "SILENT",
      "confidence": "17/20",
      "closed_at": "2026-07-18T18:09:27.729338+00:00",
      "entry_hash": "6b6c16271e8fea3f93aee11790798a74be1a2274b05ed00910c60f15ba9084b7",
      "chain_ok": 1
     },
     {
      "trace_id": "90122e28-c722-4d2e-99ad-44430ad6a87d",
      "agent_id": "L2_CARNEGIE",
      "objective": "[Carnegie/Cialdini Influence Detection] Analyze: api",
      "decision": "SILENT",
      "confidence": "17/20",
      "closed_at": "2026-07-18T18:09:27.727898+00:00",
      "entry_hash": "607fccf7645555cad6e6903e717ecd3bce764704fbe06942cc4603301bb3a935",
      "chain_ok": 1
     },
     {
      "trace_id": "62baa75b-01a5-4c23-be65-077ac75a1a78",
      "agent_id": "L1_GRICE",
      "objective": "[Grice Cooperative Principle] Analyze: api",
      "decision": "SILENT",
      "confidence": "17/20",
      "closed_at": "2026-07-18T18:09:27.726470+00:00",
      "entry_hash": "587a6b0a9f4ce5f1b60965011d56c3a26b1c837af5f14b1b8419a842a73902d9",
      "chain_ok": 1
     },
     {
      "trace_id": "47793356-3838-409e-8169-033e5ef986ec",
      "agent_id": "GATE",
      "objective": "Corroboration gate: require >= 2 active agents for any verdict above SILENT",
      "decision": "WATCH",
      "confidence": "279/1000",
      "closed_at": "2026-07-18T18:09:27.718014+00:00",
      "entry_hash": "9ce085979e2f1ac338b0a07e4a4ce42fea82f0e3a12b143a990698bf9bbaba28",
      "chain_ok": 1
     }
    ]
   }
  },
  {
   "id": "stacked",
   "label": {
    "en": "stacked scam",
    "es": "estafa apilada",
    "zh": "叠加话术"
   },
   "user_id": "attacker",
   "text": "URGENT: as your senior director I must insist. Everyone on the leadership team already approved this. If you do not wire the deposit in the next two hours the deal collapses and it will be your fault. Do not tell anyone — this is strictly confidential and only you can save it now.",
   "result": {
    "verdict": "WATCH",
    "score": {
     "exact": "81/200",
     "percent": 40
    },
    "active_agents": [
     "L1_GRICE",
     "L2_CARNEGIE",
     "L6_PEIRCE"
    ],
    "silent_agents": [
     "L3_ARISTOTLE",
     "L4_BERNE",
     "L5_LINGUISTIC"
    ],
    "crashed_agents": [],
    "recommendation": "Monitor this user's subsequent messages. Flagged for security-team review.",
    "devils_advocate": "Peirce synthesis concluded 'Deliberate obfuscation to embed influence: the message uses complex language to hide manipulation tactics, making the attempt harder to consciously identify.' based on 2/5 active layers (Grice Cooperative Principle, Carnegie/Cialdini Influence Detection). However, 3 layer(s) found no anomaly: Aristotelian Rhetoric Imbalance and Berne Transactional Analysis and Linguistic Complexity & Register. The strongest counter-hypothesis: the active layers may have fired on surface-level lexical features (urgency markers, authority claims, emotional language) that are also present in legitimate high-stakes communication — legal notices, medical advisories, crisis management. The silent dimensions suggest the underlying transaction structure and linguistic register do not deviate from baseline, which is inconsistent with systematic manipulation. This finding should be treated as WATCH rather than ALERT without additional behavioral context.",
    "audit": {
     "signal_hash": "4b8e0a14a1d09ea69c9f11df03bd9f564df9a961ad39ceb41dc4027e9e862d0c",
     "verdict_hash": "456ce8772c53914ef2c112c554d80306b3ae10113150194a0ce413d805e2b62e",
     "trace_ids": {
      "L1_GRICE": "83603ee0-328e-4469-ac93-b23aa388b9e9",
      "L2_CARNEGIE": "2f77e29c-8b52-479d-a3b5-6638163e0138",
      "L3_ARISTOTLE": "b53b9f95-31e3-4691-967b-1dad26bf7f85",
      "L4_BERNE": "1069de7f-6b77-4eb2-8bc7-29ac00748dbb",
      "L5_LINGUISTIC": "f4d5a064-8b8f-4d0c-a6a5-49b9c1218831",
      "L6_PEIRCE": "31128637-5073-4598-aa75-4e8901fea137",
      "GATE": "41e050db-773e-41ca-a2f6-b3f03dc27d19"
     },
     "chain_valid": true,
     "warnings": []
    },
    "narration": {
     "requested": true,
     "lang": "es",
     "text": null,
     "note": "Narration offline — DASHSCOPE_API_KEY not configured. The sealed verdict below is complete without it."
    }
   },
   "chain": {
    "verify": {
     "chain_ok": true,
     "errors": []
    },
    "traces": [
     {
      "trace_id": "41e050db-773e-41ca-a2f6-b3f03dc27d19",
      "agent_id": "GATE",
      "objective": "Corroboration gate: require >= 2 active agents for any verdict above SILENT",
      "decision": "WATCH",
      "confidence": "81/200",
      "closed_at": "2026-07-18T18:09:27.755049+00:00",
      "entry_hash": "e18833dd01514d07952360df909abc6ed29bd875435b9231d4c197cc73051a03",
      "chain_ok": 1
     },
     {
      "trace_id": "31128637-5073-4598-aa75-4e8901fea137",
      "agent_id": "L6_PEIRCE",
      "objective": "[Peirce Abductive Synthesis] Synthesize: api",
      "decision": "SIGNAL_DETECTED",
      "confidence": "17/20",
      "closed_at": "2026-07-18T18:09:27.753550+00:00",
      "entry_hash": "434aa75aedbd5e64e966f05c31631a6e0c2b7886bd40f0886c0d8e9b1c418d28",
      "chain_ok": 1
     },
     {
      "trace_id": "f4d5a064-8b8f-4d0c-a6a5-49b9c1218831",
      "agent_id": "L5_LINGUISTIC",
      "objective": "[Linguistic Complexity & Register] Analyze: api",
      "decision": "SILENT",
      "confidence": "17/20",
      "closed_at": "2026-07-18T18:09:27.751817+00:00",
      "entry_hash": "83c8ba6bb7dee717c2feb8216756368bc71e889b48e282c09b86863dba0e8040",
      "chain_ok": 1
     },
     {
      "trace_id": "1069de7f-6b77-4eb2-8bc7-29ac00748dbb",
      "agent_id": "L4_BERNE",
      "objective": "[Berne Transactional Analysis] Analyze: api",
      "decision": "SILENT",
      "confidence": "17/20",
      "closed_at": "2026-07-18T18:09:27.750294+00:00",
      "entry_hash": "eedbb48c3c083cf167a7ede2efa4338e5fde08667804f953b1ac615eb0dc1785",
      "chain_ok": 1
     },
     {
      "trace_id": "b53b9f95-31e3-4691-967b-1dad26bf7f85",
      "agent_id": "L3_ARISTOTLE",
      "objective": "[Aristotelian Rhetoric Imbalance] Analyze: api",
      "decision": "SILENT",
      "confidence": "17/20",
      "closed_at": "2026-07-18T18:09:27.748821+00:00",
      "entry_hash": "796e78fb5840da9122921b403ec9a51f6536addb63f8fb29719edc61446715d9",
      "chain_ok": 1
     },
     {
      "trace_id": "2f77e29c-8b52-479d-a3b5-6638163e0138",
      "agent_id": "L2_CARNEGIE",
      "objective": "[Carnegie/Cialdini Influence Detection] Analyze: api",
      "decision": "SIGNAL_DETECTED",
      "confidence": "3/10",
      "closed_at": "2026-07-18T18:09:27.746893+00:00",
      "entry_hash": "cff834addeabf9a9c9c654aff1a51442f29fcb11ac0673f5d8919a31e2d53f13",
      "chain_ok": 1
     },
     {
      "trace_id": "83603ee0-328e-4469-ac93-b23aa388b9e9",
      "agent_id": "L1_GRICE",
      "objective": "[Grice Cooperative Principle] Analyze: api",
      "decision": "SIGNAL_DETECTED",
      "confidence": "1/5",
      "closed_at": "2026-07-18T18:09:27.745524+00:00",
      "entry_hash": "1521977c03028ac9ffa259c3710f9cd343cd3671c687a12b9359547237514b18",
      "chain_ok": 1
     },
     {
      "trace_id": "fb024946-212b-45a0-9d5c-47b76babe480",
      "agent_id": "GATE",
      "objective": "Corroboration gate: require >= 2 active agents for any verdict above SILENT",
      "decision": "SILENT",
      "confidence": "3/5",
      "closed_at": "2026-07-18T18:09:27.735195+00:00",
      "entry_hash": "8d22f94885e22eb2c09fbd9d868b7c4cd124fddd67532123303788e00f366617",
      "chain_ok": 1
     }
    ]
   }
  },
  {
   "id": "pressure",
   "label": {
    "en": "soft pressure",
    "es": "presión suave",
    "zh": "软性施压"
   },
   "user_id": "recruiter",
   "text": "I rarely reach out like this, but your profile genuinely impressed me. The position closes tonight and the hiring manager asked for you specifically — I just need a small confirmation fee to hold your slot.",
   "result": {
    "verdict": "SILENT",
    "score": {
     "exact": "0/1",
     "percent": 0
    },
    "active_agents": [
     "L1_GRICE",
     "L6_PEIRCE"
    ],
    "silent_agents": [
     "L2_CARNEGIE",
     "L3_ARISTOTLE",
     "L4_BERNE",
     "L5_LINGUISTIC"
    ],
    "crashed_agents": [],
    "recommendation": "No action required. Baseline updated.",
    "devils_advocate": "Peirce synthesis concluded 'Isolated Gricean violation of maxim RELATION: Topic drift: only 5% vocabulary overlap between halves' based on 1/5 active layers (Grice Cooperative Principle). However, 4 layer(s) found no anomaly: Carnegie/Cialdini Influence Detection and Aristotelian Rhetoric Imbalance and Berne Transactional Analysis and Linguistic Complexity & Register. The strongest counter-hypothesis: the active layers may have fired on surface-level lexical features (urgency markers, authority claims, emotional language) that are also present in legitimate high-stakes communication — legal notices, medical advisories, crisis management. The silent dimensions suggest the underlying transaction structure and linguistic register do not deviate from baseline, which is inconsistent with systematic manipulation. This finding should be treated as WATCH rather than ALERT without additional behavioral context.",
    "audit": {
     "signal_hash": "d50971249762e2c0adf756bedb977bf2ebe4011becd511518216725359752a2b",
     "verdict_hash": "d1817b5f2f7fe86ecc710070a752b46d2f1b9612c63cf53ec8153c0e36962d4f",
     "trace_ids": {
      "L1_GRICE": "d0d13fbc-a6f1-426a-94a1-f7b29c23f20a",
      "L2_CARNEGIE": "3f4fe176-f93d-433b-b890-164107cf23d1",
      "L3_ARISTOTLE": "f537b732-3d25-4abb-8e8e-afbc4e8e7e56",
      "L4_BERNE": "6c69df7c-15b1-4ffb-a679-1ac32ce6f5e4",
      "L5_LINGUISTIC": "dc45d01a-98bb-45dd-ae7f-866a1afda14b",
      "L6_PEIRCE": "b38674ab-6fde-4146-872b-71bee569def7",
      "GATE": "0c38af92-6558-4446-852a-d4306b12a9d7"
     },
     "chain_valid": true,
     "warnings": []
    },
    "narration": {
     "requested": true,
     "lang": "es",
     "text": null,
     "note": "Narration offline — DASHSCOPE_API_KEY not configured. The sealed verdict below is complete without it."
    }
   },
   "chain": {
    "verify": {
     "chain_ok": true,
     "errors": []
    },
    "traces": [
     {
      "trace_id": "0c38af92-6558-4446-852a-d4306b12a9d7",
      "agent_id": "GATE",
      "objective": "Corroboration gate: require >= 2 active agents for any verdict above SILENT",
      "decision": "SILENT",
      "confidence": "3/5",
      "closed_at": "2026-07-18T18:09:27.775104+00:00",
      "entry_hash": "d4aab78c37231e185eb9c5dbf64bc4960c154eb5b7a0dcad7e7ad7e982f2f8cd",
      "chain_ok": 1
     },
     {
      "trace_id": "b38674ab-6fde-4146-872b-71bee569def7",
      "agent_id": "L6_PEIRCE",
      "objective": "[Peirce Abductive Synthesis] Synthesize: api",
      "decision": "SIGNAL_DETECTED",
      "confidence": "17/20",
      "closed_at": "2026-07-18T18:09:27.773624+00:00",
      "entry_hash": "843224cd3a3ba07d79c6aaded7d85e4b8b18c7976e085284b6426d089bbd195b",
      "chain_ok": 1
     },
     {
      "trace_id": "dc45d01a-98bb-45dd-ae7f-866a1afda14b",
      "agent_id": "L5_LINGUISTIC",
      "objective": "[Linguistic Complexity & Register] Analyze: api",
      "decision": "SILENT",
      "confidence": "17/20",
      "closed_at": "2026-07-18T18:09:27.772129+00:00",
      "entry_hash": "8269fb9524cd79d5669e75497387b610feccb57d00b5196982db255588469781",
      "chain_ok": 1
     },
     {
      "trace_id": "6c69df7c-15b1-4ffb-a679-1ac32ce6f5e4",
      "agent_id": "L4_BERNE",
      "objective": "[Berne Transactional Analysis] Analyze: api",
      "decision": "SILENT",
      "confidence": "17/20",
      "closed_at": "2026-07-18T18:09:27.770627+00:00",
      "entry_hash": "8949a9598d550de082c0de6ab6075518245412a7e33ce0cf9f28893b4264e541",
      "chain_ok": 1
     },
     {
      "trace_id": "f537b732-3d25-4abb-8e8e-afbc4e8e7e56",
      "agent_id": "L3_ARISTOTLE",
      "objective": "[Aristotelian Rhetoric Imbalance] Analyze: api",
      "decision": "SILENT",
      "confidence": "17/20",
      "closed_at": "2026-07-18T18:09:27.769120+00:00",
      "entry_hash": "241f3694b6c3f140b44512799be2211fed5f9ec9f028d5b0c1b77204dd388329",
      "chain_ok": 1
     },
     {
      "trace_id": "3f4fe176-f93d-433b-b890-164107cf23d1",
      "agent_id": "L2_CARNEGIE",
      "objective": "[Carnegie/Cialdini Influence Detection] Analyze: api",
      "decision": "SILENT",
      "confidence": "17/20",
      "closed_at": "2026-07-18T18:09:27.767623+00:00",
      "entry_hash": "cf7224fb18cb70c23aea19fb4e2f2d7df069aed8df73dd856532ce0ee54ab555",
      "chain_ok": 1
     },
     {
      "trace_id": "d0d13fbc-a6f1-426a-94a1-f7b29c23f20a",
      "agent_id": "L1_GRICE",
      "objective": "[Grice Cooperative Principle] Analyze: api",
      "decision": "SIGNAL_DETECTED",
      "confidence": "1/5",
      "closed_at": "2026-07-18T18:09:27.766145+00:00",
      "entry_hash": "058cbb6b76baa82a3c83fc41a7d3ec647cfd9a1c5cc5b18ebe98bb6eb7d288ee",
      "chain_ok": 1
     },
     {
      "trace_id": "41e050db-773e-41ca-a2f6-b3f03dc27d19",
      "agent_id": "GATE",
      "objective": "Corroboration gate: require >= 2 active agents for any verdict above SILENT",
      "decision": "WATCH",
      "confidence": "81/200",
      "closed_at": "2026-07-18T18:09:27.755049+00:00",
      "entry_hash": "e18833dd01514d07952360df909abc6ed29bd875435b9231d4c197cc73051a03",
      "chain_ok": 1
     }
    ]
   }
  }
 ]
};
